version: '3.7'

services:
  smart-brain-api:
    container_name: backend
    # image: node:11.14.0-stretch
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"